name: quiz-app-testing
on: [push]
jobs:
  quiz-app-testing-workflow:
    runs-on: ubuntu-lates
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v18.12.1
      - run: node -v
      - run: npm install
      - run: npm run test
